kind: pipeline
type: docker
name: default

trigger:
  branch:
    - droneCi
  event:
    - push


#构建过程 maven build 推送构件
steps:
  - name: test
    image: docker.1ms.run/maven:3.9.10-eclipse-temurin-21-alpine
    commands:
      - mvn clean test -P prod
    volumes:
      - name: maven-cache
        path: /root/.m2

  - name: build
  - name: package
    image: docker.1ms.run/maven:3.9.10-eclipse-temurin-21-alpine
    commands:
      - mvn package -P prod
    volumes:
      - name: maven-cache
        path: /root/.m2

  - name: deploy
    image: drillster/drone-rsync
    environment:
      HOST:
        from_secret: DEPLOYIP
      USERNAME:
        from_secret: DEPLOYUSERNAME
      PASSWORD:
        from_secret: DEPLOYPASSWORD
    settings:
      hosts: [ $HOST ]
      source: ./target
      target: /home/onepractice/
      include: [ "onepractice-0.0.1-SNAPSHOT.jar"]

  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: DEPLOYIP
      username:
        from_secret: DEPLOYUSERNAME
      password:
        from_secret:
          from_secret: DEPLOYPASSWORD
      port: 22
      command_timeout: 2m
      script:
        - docker restart onepractice
