kind: pipeline
type: docker
name: default

trigger:
  branch:
    - droneCi
  event:
    - push


#构建过程 maven build 推送构件
steps:
  - name: test
    image: docker.1ms.run/maven:3.9.10-eclipse-temurin-21-alpine
    commands:
      - mvn clean test -P prod
    volumes:
      - name: maven-cache
        path: /root/.m2

  - name: package
    image: docker.1ms.run/maven:3.9.10-eclipse-temurin-21-alpine
    commands:
      - mvn package -P prod
    volumes:
      - name: maven-cache
        path: /root/.m2



  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: DEPLOYIP
      username:
        from_secret: DEPLOYUSERNAME
      password:
        from_secret: DEPLOYPASSWORD
      port: 22
      target: /home/onepractice/
      source: /drone/src/target/onepractice-0.0.1-SNAPSHOT.jar

  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: DEPLOYIP
      username:
        from_secret: DEPLOYUSERNAME
      password:
          from_secret: DEPLOYPASSWORD
      port: 22
      command_timeout: 2m
      script:
        - docker restart onepractice

volumes:
  - name: maven-cache
    host:
      path: /data/cache/maven