kind: pipeline
type: docker
name: default

trigger:
  branch:
    - droneCi
  event:
    - push


#构建过程 maven build 推送构件
steps:
  - name: test
    image: docker.1ms.run/maven:3.9.10-eclipse-temurin-21-alpine
    commands:
      - mvn clean test -P prod
  - name: package
    image: docker.1ms.run/maven:3.9.10-eclipse-temurin-21-alpine
    commands:
      - mvn clean package -P prod