kind: pipeline
type: docker
name: default

trigger:
  branch:
    - droneCi
  event:
    - push


#构建过程 maven build 推送构件
steps:
  - name: test
    image: docker.1ms.run/maven:3.9.10-eclipse-temurin-21-alpine
    commands:
      - wget https://r2.126386.xyz/application.yml -O src/main/resources/application.yml
      - wget https://r2.126386.xyz/application-prod.yml -O src/main/resources/application-prod.yml
      - mvn clean test -P prod
    volumes:
      - name: maven-cache
        path: /root/.m2

  - name: package
    image: docker.1ms.run/maven:3.9.10-eclipse-temurin-21-alpine
    commands:
      - mvn package -P prod
    volumes:
      - name: maven-cache
        path: /root/.m2

  - name: upload r2
    image: plugins/s3
    settings:
      bucket: onepractice
      endpoint:
        from_secret: R2_ENDPOINT
      access_key:
        from_secret: R2_ACCESS_KEY
      secret_key:
        from_secret: R2_SERCRET_KEY
      region: APAC
      strip_prefix: /drone/src/target/
      source: /drone/src/target/*.jar
      target: /


  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: DEPLOYIP
      username:
        from_secret: DEPLOYUSERNAME
      password:
          from_secret: DEPLOYPASSWORD
      port: 22
      command_timeout: 2m
      script:
        - /home/onepractice/run.sh

volumes:
  - name: maven-cache
    host:
      path: /data/cache/maven