spring:
  application:
    name: one-practice
  profiles:
    include: redisson
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.1:3306/onepractice?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: Luchen1122
  data:
    redis:
      port: 6379
      host: 192.168.100.1
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-idle: 10
          min-idle: 0
          max-wait: -1ms
  mail:
    host: smtp.qq.com
    username: 1263868407@qq.com
    password: kpcvdvgmuoxhjecc
    port: 465
    ssl:
      enabled: true
    protocol: smtp
    default-encoding: UTF-8

easy-query:
  database: mysql
  name-conversion: underlined
  default-track: true
server:
  port: 8080
sa-token:
  token-name: token
  timeout: 2592000
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true
